import pandas as pd
from fpdf import FPDF
from datetime import datetime


def generate_pdf_report(df: pd.DataFrame, insights: str) -> bytes:
    """Generate a PDF report of the data analysis."""
    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(102, 126, 234)
    pdf.cell(0, 14, "AI Data Analysis Report", ln=True, align="C")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(
        0, 8,
        f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}",
        ln=True, align="C"
    )
    pdf.ln(6)

    # Dataset Overview
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 10, "Dataset Overview", ln=True)
    pdf.set_draw_color(102, 126, 234)
    pdf.set_line_width(0.8)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    stats = [
        ("Total Rows", f"{df.shape[0]:,}"),
        ("Total Columns", str(df.shape[1])),
        ("Missing Values", f"{df.isnull().sum().sum():,}"),
        ("Duplicate Rows", f"{df.duplicated().sum():,}"),
        ("Numeric Columns", str(len(df.select_dtypes(include='number').columns))),
        ("Categorical Columns", str(len(df.select_dtypes(include='object').columns))),
    ]

    for label, value in stats:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(70, 8, f"{label}:", ln=False)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, value, ln=True)
    pdf.ln(4)

    # Statistical Summary
    numeric_cols = df.select_dtypes(include='number').columns.tolist()
    if numeric_cols:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(0, 10, "Statistical Summary", ln=True)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)

        desc = df[numeric_cols[:5]].describe().round(2)
        col_width = min(35, 180 // (len(desc.columns) + 1))

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(230, 230, 255)
        pdf.cell(30, 7, "Stat", border=1, fill=True)
        for col in desc.columns:
            pdf.cell(col_width, 7, str(col)[:10], border=1, fill=True)
        pdf.ln()

        pdf.set_font("Helvetica", "", 9)
        for idx, row in desc.iterrows():
            pdf.cell(30, 7, str(idx), border=1)
            for val in row.values:
                pdf.cell(col_width, 7, str(round(val, 2)), border=1)
            pdf.ln()
        pdf.ln(4)

    # AI Insights
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 10, "AI-Generated Insights", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    clean = insights.replace("**","").replace("##","").replace("#","").replace("*","-")
    pdf.multi_cell(0, 7, clean)

    # Footer
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(
        0, 10,
        "Generated by AI Data Analyst | Powered by Gemini AI & Streamlit",
        align="C"
    )

    return bytes(pdf.output())